const userActionTypes = {
    USER_SIGN_IN: 'USER_SIGN_IN',
    USER_ALREADY_SIGNED: 'USER_ALREADY_SIGNED',
    USER_SIGN_OUT: 'USER_SIGN_OUT',
    SET_USER_INFO: 'SET_USER_INFO',
    SAVE_USER_PROFILE: 'SAVE_USER_PROFILE',
}

export default userActionTypes;